In [1]:
import pandas as pd

In [3]:
data=pd.read_csv('edited lines.csv')

In [4]:
data

,Date,Home Team,Away Team,Home Score,Away Score,Playoff Game?,Home Odds Open,Away Odds Open,Home Line Open,W-L,...,Defense DVOA Rank.1,Defense DVOA.1,Defense Weighted DVOA Rank.1,Defense Weighted DVOA.1,Special Teams DVOA Rank.1,Special Teams DVOA.1,Special Teams Weighted DVOA Rank.1,Special Teams Weighted DVOA.1,Unnamed: 43,Unnamed: 44
0,2021-02-07,TB,KC,31,9,Y,2.55,1.57,3.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-24,KC,BUF,38,24,Y,1.66,2.30,-2.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-24,GB,TB,26,31,Y,1.50,2.70,-4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-17,NO,TB,20,30,Y,1.52,2.67,-3.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-17,KC,CLE,22,17,Y,1.20,4.75,-10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4002,2006 Week 1,DET,SEA,6,9,NaN,3.50,1.33,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4003,2006 Week 1,CLE,NO,14,19,NaN,1.50,2.75,-3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,2006 Week 1,CAR,ATL,6,20,NaN,1.43,2.90,-4.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,2006 Week 1,ARI,SF,34,27,NaN,1.18,5.00,-9.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,2006 Week 1,PIT,MIA,28,17,NaN,1.80,2.05,-1.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
grouped = data.groupby(data.Date)

In [6]:
grouped

In [11]:
for i in range(2):
    week1 = grouped.get_group("2006 Week 1")

In [12]:
week1

,Date,Home Team,Away Team,Home Score,Away Score,Playoff Game?,Home Odds Open,Away Odds Open,Home Line Open,W-L,...,Defense DVOA Rank.1,Defense DVOA.1,Defense Weighted DVOA Rank.1,Defense Weighted DVOA.1,Special Teams DVOA Rank.1,Special Teams DVOA.1,Special Teams Weighted DVOA Rank.1,Special Teams Weighted DVOA.1,Unnamed: 43,Unnamed: 44
3990,2006 Week 1,ATL,TB,14,3,NaN,1.44,2.85,-4.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3991,2006 Week 1,WAS,MIN,16,19,NaN,1.48,2.80,-4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3992,2006 Week 1,OAK,SD,0,27,NaN,2.40,1.63,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3993,2006 Week 1,TEN,NYJ,16,23,NaN,1.63,2.40,-3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3994,2006 Week 1,TB,BAL,0,27,NaN,1.63,2.45,-3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3995,2006 Week 1,STL,DEN,18,10,NaN,2.75,1.50,3.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3996,2006 Week 1,NYG,IND,21,26,NaN,2.40,1.63,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3997,2006 Week 1,NE,BUF,19,17,NaN,1.17,5.25,-9.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3998,2006 Week 1,KC,CIN,10,23,NaN,1.77,2.10,-1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3999,2006 Week 1,JAX,DAL,24,17,NaN,2.10,1.77,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4000,2006 Week 1,HOU,PHI,10,24,NaN,3.50,1.33,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4001,2006 Week 1,GB,CHI,0,26,NaN,2.80,1.48,3.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4002,2006 Week 1,DET,SEA,6,9,NaN,3.50,1.33,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4003,2006 Week 1,CLE,NO,14,19,NaN,1.50,2.75,-3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,2006 Week 1,CAR,ATL,6,20,NaN,1.43,2.90,-4.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,2006 Week 1,ARI,SF,34,27,NaN,1.18,5.00,-9.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,2006 Week 1,PIT,MIA,28,17,NaN,1.80,2.05,-1.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN